webapp/patient/models.py
from sqlalchemy import Column, Integer, String, Date
from webapp.db import Base


class Patient(Base):
    __tablename__ = "patient"
    
    id = Column(Integer, primary_key = True)
    first_name = Column(String)
    last_name = Column(String)
    surname = Column(String)
    address = Column(String)
    date_of_birth = Column(Date)
    
    
    def __repr__(self):
        return f"Patient {self.id} {self.first_name} {self.last_name}"

webapp/patient/forms.py
from flask_wtf import FlaskForm
from wtforms import  StringField, SubmitField, DateTimeField
from wtforms.validators import DataRequired
from webapp.utilits import create_patient
from datetime import datetime


class NewPatient(FlaskForm):
    #patient = create_patient()
    first_name = StringField("Имя", validators=[DataRequired()], render_kw={"class": "form-control"})
    last_name = StringField("Фамилия", validators=[DataRequired()], render_kw={"class": "form-control"})
    surname = StringField("Отчество", validators=[DataRequired()], render_kw={"class": "form-control"})
    date_of_birth = StringField("Дата рождения", validators=[DataRequired()], render_kw={"class": "form-control"})
    address = StringField("Адрес", validators=[DataRequired()], render_kw={"class": "form-control"})
    cause = StringField("Повод к вызову", validators=[DataRequired()], render_kw={"class":"form-control"})
    submit = SubmitField("Создать карту вызова", render_kw={"class": "btn btn-primary"})

class Time(FlaskForm):
    current_time=datetime.now().strftime("%H:%M")
    time_of_receipt =  DateTimeField("Время приёма", format = "%H:%M")
    transmission_time = DateTimeField("Время передачи", format = "%H:%M")
    departure_time = DateTimeField("Время принятия вызова", format = "%H:%M")
    arrival_time = DateTimeField("Время прибытия", format = "%H:%M")
    start_time_of_hospitalization = DateTimeField("Время начала госпитализации", format = "%H:%M")
    time_of_arrival_at_hospital = DateTimeField("Время прибытия в стационар", format = "%H:%M")
    call_end_time = DateTimeField("Окончание вызова", format = "%H:%M")
    

webapp/card/views.py
from flask import render_template,redirect,url_for,request
from flask import Blueprint
from webapp.models import DiagnosisCode
from webapp.card.forms import CardForm
from webapp.patient.models import Patient
from webapp.card.models import CardOne

from webapp.config import conn
from webapp.utilits import save_card,update_time,data_dict, remove_data_dict
from psycopg2 import Error

my_cur = conn.cursor()

blueprint = Blueprint('card', __name__, url_prefix='/cards')

@blueprint.route('/main_card', methods=["GET", 'POST'])
def main_card():
  form = CardForm()
  title = "Карта"
  mkb_code =  DiagnosisCode.query.all()
  if request.method == "POST":
    mkb = request.form.get('mkb')
    save_card(table_name="card_united", conn=conn,data_dict=data_dict)
  return render_template('main_card.html',page_title = title, form_general=form, mkb_code=mkb_code)

@blueprint.route('/finished_card', methods=["GET", 'POST'])
def finished_card():
  my_cur.execute("SELECT * FROM card_united WHERE id IN (SELECT MAX(id) FROM card_united)")
  data = my_cur.fetchall()
  print(data)
  my_cur.execute("SELECT * FROM Users WHERE id = (SELECT doctor_id FROM card_united ORDER BY id DESC LIMIT 1)")
  data_doctor = my_cur.fetchall()
  my_cur.execute("SELECT * FROM patient WHERE id = (SELECT patient_id FROM card_united ORDER BY id DESC LIMIT 1)")
  data_patient = my_cur.fetchall()
  if request.method=="POST":
    remove_data_dict(data_dict=data_dict)
    print("на главной")
    return redirect(url_for("user.main"))
  return render_template('finished_card.html', data=data, data_doctor=data_doctor, data_patient = data_patient)

@blueprint.route("/update_time", methods=["GET", 'POST'])
def update():
  if request.method=="POST":
    update_time("card_united", conn=conn,data_dict=data_dict)
    return redirect(url_for("card.finished_card"))
  else:
    return redirect(url_for("patient.create"))

@blueprint.route("/history",methods=["GET",'POST'])
def history():
  card_data = CardOne.query.filter(CardOne.doctor_id == data_dict['doctor_id']).all()
  patient_data = []
  if request.method == "GET":
    print(len(card_data))
    for i in card_data:
      print(i.diagnosis)
      qu = Patient.query.filter(Patient.id == i.patient_id).first()
      join = [i.date_card, qu.last_name,qu.first_name,i.diagnosis]
      patient_data.append(join)
      if qu == None:
        continue
      # else:
      #   print(qu.last_name, qu.date_of_birth)
    patient_data = sorted(patient_data, key = lambda x: x[0][-2:])
    print(patient_data)
    return render_template("history.html", data = patient_data, card_data = card_data)
  return render_template('history.html', data=patient_data, card_data = card_data)
  

webapp/patient/views.py
from flask import render_template
from flask import Blueprint
from webapp.patient.forms import NewPatient, Time
from webapp.utilits import add_time,save_patient,data_dict,remove_data_dict
from webapp.patient.forms import NewPatient, Time
from flask import request


blueprint = Blueprint('patient', __name__, url_prefix='/new_patient')

@blueprint.route('/create', methods=['POST', 'GET'])
def create():
  title = "Пациент"
  time_form = Time()
  patient_form = NewPatient()
  
  if request.method == 'POST':
    print(id(data_dict))
    index = request.form["index"]
    add_time(index,data_dict)
    return render_template("patient.html",page_title=title, 
                           form=patient_form, time_form = time_form, 
                           time = data_dict)
  else:
    print("GET")
    save_patient(patient_form,data_dict)
    return render_template("patient.html",page_title=title, 
                           form=patient_form, time_form = time_form, 
                           time = data_dict)

         
    

webapp/user/views.py
import sys
from datetime import datetime

from flask import flash, render_template, redirect, url_for, request
from flask_login import login_user, logout_user, current_user
from flask import Blueprint

from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import Users
from webapp.card.forms import CardForm
from webapp.card.models import CardOne
from webapp.db import Base, db_session
from webapp.utilits import data_dict,save_doctor, save_patient



blueprint = Blueprint('user', __name__, url_prefix='/users')


@blueprint.route('/login', methods=['POST', "GET"])
def login():
  title = "Войти"
  login_form = LoginForm()
  return render_template('login.html', page_title=title, form=login_form)

@blueprint.route('/process-login', methods=['POST'])
def process_login():
  form = LoginForm()
  if form.validate_on_submit():
    password = form.password_entry.data
    user = Users.query.filter(Users.username == form.username.data).first()
    sys.stdout.flush()
    print(f'Результат работы функции check_password: {user.check_password(password)}')
    if user and user.check_password(password):
      login_user(user, remember=form.remember_me.data) #запоминание пользователя
      print("Уcпех")
      flash("Вы успешно вошли на сайт")
      print(f"ID пользователя: {current_user.id}, {current_user.role}")
      save_doctor(data_dict=data_dict)
      if current_user.role == "Врач":
        return redirect(url_for('user.main'))
      elif current_user.role == "Админ":
        return redirect(url_for("user.main"))
      else:
        return redirect(url_for("user.main_dispatcher"))
  print("Ошибка")
  flash("Неправильное имя пользователя или пароль")
  return redirect(url_for('user.login'))

@blueprint.route('/main')
def main():
  return render_template('main.html')

@blueprint.route('/logout')
def logout():
  flash("Вы разлогинились")
  logout_user()
  return redirect(url_for('user.login'))

@blueprint.route('/register')
def register():
  if  not current_user.is_authenticated:
    form = RegistrationForm()
    title = "Регистрация"
    return render_template('registration.html', page_title=title, form=form)
  print(f"ID текущего доктора: {current_user.id}")
  return redirect(url_for('user.login'))
  

@blueprint.route('/register', methods=["POST", "GET"])
def process_reg():
  form = RegistrationForm()
  if form.validate_on_submit():
    new_user = Users(username=form.username.data, first_name=form.name.data, last_name=form.lastname.data, role=form.role.data, surname = form.surname.data)
    new_user.set_password(form.password.data)
    db_session.add(new_user)
    db_session.commit()
    flash("Вы зарегистрировались!")
    
    return redirect(url_for('user.login'))
  flash("Исправьте ошибки в форме")
  return redirect(url_for('user.register'))

@blueprint.route('/dispatcher/new_card', methods=["POST","GET"])
def new_card():
  current_time=datetime.now().strftime("%H:%M")
  form = CardForm(current_time=current_time)
  if request.method == "POST":
    form.save_card(request)
    return redirect(url_for("user.main_dispatcher"))
  return render_template("dispatcher.html", form = form)
  
  

@blueprint.route('/dispatcher/main', methods=["POST","GET"])
def main_dispatcher():
  data_card = CardOne.query.filter(CardOne.status == "Принят").all()
  form = CardForm()
  data = []
  for card in data_card:
      print(card)
      join = [card.last_name,card.first_name,card.surname,card.status, card.crew]
      data.append(join)
  if request.method == "POST":
    return redirect(url_for('user.new_card'))
  elif request.method == "GET":
    print("GET")
    print(data)
    return render_template("dispatcher_main.html", data=data, form = form)

# def card_process():
#   card = CardForm()




webapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head> 
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='font-awesome.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <title>{{page_title}}</title>
</head>
<body>
    {% include "menu_bar.html" %}
    <div>
    {% block content %}
    {% endblock %}
    </div>
  <script src="js/bootstrap.bundle.min.js"></script>
</body>
</html>

webapp/templates/dispatcher.html
{%  extends "base.html" %}

{%  block content %}
<div class="container">
    <div class="patient col-6" style='margin-top: 35px;'>
      <h1>Данные пациента</h1>
      <form action="{{ url_for('user.new_card') }}" method="POST">
        
        {{form.last_name.label()}}{{form.last_name()}}
        {{form.first_name.label()}}{{form.first_name()}}
        {{form.surname.label()}}{{form.surname()}}
        {{form.date_of_birth.label()}}{{form.date_of_birth()}}
        {{form.address.label()}}{{form.address()}}<br>
        {{form.cause.label()}}{{form.cause()}}<br>
        {{form.status.label()}}{{form.status()}}<br>
        <br>
        {{form.submit}}
      </form>

    </div>
</div>
{%  endblock    %}

webapp/templates/dispatcher_main.html
{%  extends "base.html" %}

{%  block content %}
<div class="container">
    <div class="patient col-6" style='margin-top: 35px;'>
      <h1>Вызова</h1>
      <form action="{{ url_for('user.new_card') }}" methods="POST">
        
        {{form.goto_create}}
      </form>
      
    </div>
    <form action="{{url_for('user.main_dispatcher')}}" methods="GET">
        <button type="button" class="btn btn-primary">Обновить</button>
            {%for card in data%}
            <h2>{{card[0]}} {{card[1]}} {{card[2]}} {{card[3]}} {{form.crew}}</h2><br>
            {% endfor %}
    </form>
</div>
{%  endblock    %}

webapp/templates/history.html
{%  extends "base.html" %}

{% block content %}
<div class="container">
    <div class="patient col-6" style='margin-top: 35px;'>
    <h1>История</h1>
        <form action="{{ url_for('card.history') }}" method="GET">
            {% for row in data %}
            <div><p>Пациент: {{row[0]}} {{row[1]}} {{row[2]}} {{row[3]}}
                <from action ='{{ url_for("card.update") }}' method="POST"><button>Редактировать</button>
                </from>
                </p>
            </div>
            {% endfor %}
        </form>
    </div>
</div>


{% endblock %}

webapp/templates/login.html
{% include "base.html" %}

{% block content %}

  <div class="container" style='margin-left: auto; margin-right: auto;'>
    <div class="col-lg-3 bg-white m-auto rounded-top">
      <h2 class="text-center pt-3 header-title">Войти</h2>
      <p class="text-center text-muted lead mt-3 mb-4 fs-5">
        Нет аккаунта?  
        <span class="login-link"><a href="{{ url_for('user.register') }}" class="login-btn px-2">Зарегистрироваться</a></span>
      </p>
      {% with messages = get_flashed_messages() %}
      {% if messages %}
      <ul class="flash-messages">
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
      </ul>    
      {% endif %}
      {% endwith %}
      <!--Form start-->
      <div class="form">
      <form action="{{ url_for('user.process_login') }}" method="POST">
        {{ form.csrf_token }}
        <div class="form-group mb-3" style='margin-left: auto; margin-right: auto'>
          {{ form.username() }} <!--Пароль-->
        </div>
        <div class="form-group mb-3"  style='margin-left: auto; margin-right: auto'>
          {{ form.password_entry() }} <!--Пароль-->
        </div>
        <div class="form-group form-check"  style='margin-left: auto; margin-right: auto;'>
          <p>{{ form.remember_me() }} {{ form.remember_me.label(class_ = "form-check-label") }}</p>
        </div>
        <div class="mt-4 mx-auto" style="width: 100px;"  style='margin-left: auto; margin-right: auto'>
        {{ form.submit() }}
        </div>
      </form>
    </div>
    </div>
  </div>

{% endblock %}

webapp/templates/main.html
{% extends "base.html" %}

{% block content %}
  <div class='container'>
    <button type="button" class="btn btn-primary">
      <a href="#" class='text-white'>Кнопка</a>
    </button>
    <button type="button" class="btn btn-primary"><a href="{{url_for("card.history")}}" class='text-white'>История</a></button>
    <form action="{{ url_for('patient.create') }}" method="GET">
      <button type="submit" class="btn btn-primary">Принять вызов</a></button>
    </form>
  </div>
{% endblock %}

webapp/templates/menu_bar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Медицинские карты</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
          {% if current_user.is_authenticated %}
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{url_for("user.main")}}">Главная страница</a>
          </li>
          <li class="nav-item">
          <a class="nav-link" href="{{url_for("user.logout")}}">Выйти</a>
          </li>
          {% else%}
          <li class="nav-item">
          <a class="nav-link" href="{{url_for("user.login")}}">Войти</a>
          </li>
          {%endif%}
        </li>
        
        </li>
      </ul>
    </div>
  </div>
</nav>

webapp/templates/patient.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
      <div class="patient col-4" style='margin-top: 35px;'>
        <h1>Данные пациента</h1>
        <form action="{{ url_for('card.main_card') }}" methor="POST">
          {{ form.hidden_tag() }}
          {{form.last_name.label()}}{{form.last_name()}}
          {{form.first_name.label()}}{{form.first_name()}}
          {{form.surname.label()}}{{form.surname()}}
          {{form.date_of_birth.label()}}{{form.date_of_birth()}}
          {{form.address.label()}}{{form.address()}}<br>
          {{form.submit}}
        </form>
      </div>
      <div class='time col-4' style='margin-top: 35px;'>
        <h2>Время</h2>
        <form action="{{url_for('patient.create')}}" method="POST">
          <input type = "hidden" name="index" value = "time_of_receipt">
          <h3><button type="button" class="btn btn-secondary" disabled>Время приёма вызова</button>
          {{time_form.time_of_receipt(value = time["time_of_receipt"])}}</h3>
          <br>
          <input type = "hidden" name="index" value = "transmission_time">
          <h3><button type="button" class="btn btn-secondary" disabled>Время передачи вызова</button>
          {{time_form.transmission_time(value = time["transmission_time"])}}</h3>
          <br>
        </form>

        <form action="{{url_for('patient.create')}}" method="POST"  style='margin-top: 20px;'>
        <input type = "hidden" name="index" value = "departure_time">
        {%if time["departure_time"] == None %}<button type="submit" class="btn btn-primary">Время принятия вызова</button>{% endif %}
        {%if time["departure_time"] != None %}<h3><button type="button" class="btn btn-secondary" disabled>Время принятия вызова</button>
        {{time_form.departure_time(value = time["departure_time"])}}</h3>{%endif%}
        <br>
        </form>

        <form action="{{url_for('patient.create')}}" method="POST"  style='margin-top: 20px;'>
          <input type = "hidden" name="index" value = "arrival_time">
          {%if time["arrival_time"] == None %}<button type="submit" class="btn btn-primary">Время прибытия на вызов</button>{% endif %}
          {%if time["arrival_time"] != None %}<h3><button type="button" class="btn btn-secondary" disabled>Время прибытия на вызов</button>
          {{time_form.arrival_time(value = time["arrival_time"])}}</h3>{%endif%}
          <br>
        </form>

        <form action="{{url_for('patient.create')}}" method="POST"  style='margin-top: 20px;'>
          <input type = "hidden" name="index" value = "start_time_of_hospitalization">
          {%if time["start_time_of_hospitalization"] == None %}<button type="submit" class="btn btn-primary">Время начала госпитализации</button>{% endif %}
          {%if time["start_time_of_hospitalization"] != None %}<h3><button type="button" class="btn btn-secondary" disabled> Время начала госпитализации </button> 
          {{time_form.start_time_of_hospitalization(value = time["start_time_of_hospitalization"])}}</h3>{%endif%}
          <br>
        </form>

        <form action="{{url_for('patient.create')}}" method="POST"  style='margin-top: 20px;'>
          <input type = "hidden" name="index" value = "time_of_arrival_at_hospital">
          {%if time["time_of_arrival_at_hospital"] == None %}<button type="submit" class="btn btn-primary" >Время прибытия в стационар</button>{% endif %}
          {%if time["time_of_arrival_at_hospital"] != None %}<h3><button type="button" class="btn btn-secondary" disabled>Время прибытия в стационар</button>
          {{time_form.time_of_arrival_at_hospital(value = time["time_of_arrival_at_hospital"])}}</h3>{% endif %}
        
          <br>
        </form>
        <form action="{{url_for('patient.create')}}" method="POST"  style='margin-top: 20px;'>
          <input type = "hidden" name="index" value = "call_end_time">
          {% if time["call_end_time"] == None %}<button type="submit" class="btn btn-primary" >Время окончания</button>{% endif %}
          {%if time["call_end_time"] != None %}<h3><button type="button" class="btn btn-secondary" disabled>Время окончания</button>
          {{time_form.call_end_time(value = time["call_end_time"])}}</h3>{%endif%}
          <br>
        </form>
        <form action="{{url_for('card.update')}}" method="POST"  style='margin-top: 20px;'>
          <button tyoe="submit" class="btn btn-primary"> Завершить вызов<button>
        </form>
      </div>
    </div>
{% endblock %}

webapp/templates/registration.html
{% extends "base.html" %}

{% block content %}

  <div class="container">
    <div class="col-lg-4 bg-white m-auto rounded-top">
      <h2 class="text-center pt-3 header-title">Зарегистрироваться</h2>
      <p class="text-center text-muted lead mt-3 mb-4 fs-5">
        Уже есть аккаунт? 
        <span class="login-link"><a href="{{url_for('user.login')}}" class="login-btn px-2">Войти</a></span>
      </p>
      <!--Form start-->
      <form action="#" method="POST">
        {{ form.csrf_token }}
        <div class="input-group mb-3">
          <span class="input-group-text"><img src="{{ url_for('static', filename='images/account_circle_FILL0_wght400_GRAD0_opsz24.svg') }}" alt=""></span>
          {{ form.username() }} <!--Ник-->
        </div>
        <div class="input-group mb-3">
          <span class="input-group-text"><img src="{{ url_for('static', filename='images/person_FILL0_wght400_GRAD0_opsz24.svg') }}" alt=""></span>
          {{ form.name()}} <!--Имя-->
        </div>
        <div class="input-group mb-3">
          <span class="input-group-text"><img src="{{ url_for('static', filename='images/person_FILL0_wght400_GRAD0_opsz24.svg') }}" alt=""></span>
          {{ form.surname()}} <!--Отчество-->
        </div>
        <div class="input-group mb-3">
          <span class="input-group-text"><img src="{{ url_for('static', filename='images/person_FILL0_wght400_GRAD0_opsz24.svg') }}"> </span>
          {{ form.lastname() }} <!--Фамилия-->
        </div>
        <div class="form-group mb-3">
          <span class="input-radio" list-style="none"><img src="{{ url_for('static', filename='images/person_FILL0_wght400_GRAD0_opsz24.svg') }}"></span>
          {{ form.role()}} <!--Должность-->
        </div>
        <div class="input-group mb-3">
          <span class="input-group-text"><img src="{{ url_for('static', filename='images/lock_FILL0_wght400_GRAD0_opsz24.svg') }}" alt=""></span>
          {{ form.password() }} <!--Пароль-->
        </div>
        <div class="input-group mb-3">
          <span class="input-group-text"><img src="{{ url_for('static', filename='images/lock_FILL0_wght400_GRAD0_opsz24.svg') }}" alt=""></span>
          {{ form.password_2() }} <!--Повторить пароль-->
        </div>

        <div class="d-grid">
          {{ form.submit() }} <!--Кнопка отвправить-->
        </div>

      </form>
    </div>
  </div>

{% endblock %}